# v2 syntax
version: '2'

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=accordous
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=laravel-test-backend

  # Redis
  redis:
    image: redis:5-alpine
    container_name: test-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Caddy)
  api:
    image: ambientum/php:7.2-nginx
    container_name: test-api
    volumes:
      - ./api:/var/www/app
    ports:
      - "80:8080"
    depends_on:
      - mysql
    links:
      - mysql
 
  # Laravel Queue Worker
  queue:
    image: ambientum/php:7.2
    container_name: test-queue
    volumes:
      - ./api:/var/www/app
    command:
      - php
      - artisan
      - queue:work
    links:
      - mysql
      - redis

# Named volumes
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local  
